// Generated by https://quicktype.io

export interface Restaurant {
  id: number;
  rating: Rating;
  name: string;
  type: string;
  tables_available: number;
  location: string;
  n_comments: number;
}

export interface Rating {
  number: number;
  avg: number;
  max: number;
}
